### ISSUE TITLE
get_bus_demand cannot be called using Scenario in create state

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#421]
```python
>>> from powersimdata.scenario.scenario import Scenario
>>> scenario = Scenario('')
>>> scenario.state.set_builder(interconnect="Texas")
Transferring ScenarioList.csv from server
100%|#######################################| 543k/543k [00:00<00:00, 4.42Mb/s]
Reading bus.csv
Reading plant.csv
Reading gencost.csv
Reading branch.csv
Reading dcline.csv
Reading sub.csv
Reading bus2sub.csv
Reading zone.csv
--> Summary
# Existing study
test | base | Anchor | Julia | Texas_Crisis
# Available profiles
demand: vJan2021
hydro: vJan2021
solar: vJan2021
wind: vJan2021
>>> scenario.state.builder.set_base_profile("demand", "vJan2021")
>>> scenario.state.get_bus_demand()
--> Loading demand
demand_.csv not found in C:\Users\DanielOlsen\ScenarioData\ on local machine
Traceback (most recent call last):
  File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\input\input_data.py", line 76, in get_data
    data = _read_data(filepath)
  File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\input\input_data.py", line 128, in _read_data
    data = pd.read_csv(filepath, index_col=0, parse_dates=True)
  File "C:\Python38\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Python38\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Python38\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Python38\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Python38\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Python38\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Python38\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DanielOlsen\\ScenarioData\\raw/usa_tamu\\demand_.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\scenario\create.py", line 153, in get_bus_demand
    return get_bus_demand(self._scenario_info, grid)
  File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\input\input_data.py", line 147, in get_bus_demand
    demand = InputData().get_data(scenario_info, "demand")
  File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\input\input_data.py", line 82, in get_data
    self.data_access.copy_from(file_name, from_dir)
  File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\data_access\data_access.py", line 267, in copy_from
    self._check_file_exists(from_path, should_exist=True)
  File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\data_access\data_access.py", line 68, in _check_file_exists
    raise OSError(f"{filepath} {msg} on server")
OSError: /mnt/bes/pcm/raw/usa_tamu/demand_.csv not found on server
```

**Comment by rouille** [comment]
That is weir because the `get_bus_demand` function uses the same methodology than the `get_demand`method of the `Create` class and it sorks:
```
>>> scenario.state.get_demand()
--> Loading demand
                         301      302       303      304       305      306       307      308
UTC Time                                                                                      
2016-01-01 00:00:00  2173.81  868.636  1229.210  3340.36  13411.90  6312.75  10703.60  1341.75
2016-01-01 01:00:00  2206.96  890.951  1269.140  3434.01  13768.30  6567.96  10743.70  1449.53
2016-01-01 02:00:00  2200.80  873.921  1252.890  3325.39  13413.20  6410.27  10436.60  1355.51
2016-01-01 03:00:00  2179.30  860.342  1234.950  3178.55  13004.20  6186.77  10117.10  1314.45
2016-01-01 04:00:00  2154.41  840.609  1215.900  3054.40  12578.40  5919.27   9836.11  1330.87
...                      ...      ...       ...      ...       ...      ...       ...      ...
2016-12-31 19:00:00  2047.46  690.663   972.531  2753.51  10261.60  5224.35   9651.34  1142.80
2016-12-31 20:00:00  2035.04  675.303   956.366  2786.11  10060.70  5172.49   9639.12  1125.27
2016-12-31 21:00:00  2026.89  668.133   952.482  2824.33   9993.34  5227.41   9637.84  1124.05
2016-12-31 22:00:00  2023.91  674.449   954.350  2854.74  10078.60  5306.91   9683.47  1118.78
2016-12-31 23:00:00  2032.57  705.709   976.030  2914.22  10665.70  5540.72  10066.90  1176.70

[8784 rows x 8 columns]
```
